#pragma config(Sensor, in1,    rightGyro,      sensorGyro)
#pragma config(Sensor, in2,    leftGyro,       sensorGyro)
#pragma config(Sensor, in3,    mobileAngle,    sensorPotentiometer)
#pragma config(Sensor, in4,    armSwingAngle,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightLights,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  leftLights,     sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMid,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mobileGoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armBase,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armSwing,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           grabber,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftMid,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void leftDrive(short speed)
{
	motor[leftFront] = speed;
	motor[leftMid] = speed;
	motor[leftBack] = speed;
}

void rightDrive(short speed)
{
	motor[rightFront] = speed;
	motor[rightMid] = speed;
	motor[rightBack] = speed;
}


task main()
{
	SensorType[in1] = sensorNone;
	SensorType[in2] = sensorNone;
	wait1Msec(1000);
	SensorType[in1] = sensorGyro;
	SensorType[in2] = sensorGyro;
	wait1Msec(2000);

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


	short leftSpeed;
	short rightSpeed;


	while(true)
	{
		/*				!!!		DRIVE CONTROLS		!!!
		* The main remote should only control the mobile goal arm and
		* drives the robot around.
		*/
		//To control the left side using channel 3
		if (vexRT[Ch3] > -25 && vexRT[Ch3] < 25)
		{
			leftSpeed = 0;
		}
		else
		{
			leftSpeed = vexRT[Ch3];
		}

		//To control the right side using channel 2
		if (vexRT[Ch2] > -25 && vexRT[Ch2] < 25)
		{
			rightSpeed = 0;
		}
		else
		{
			rightSpeed = vexRT[Ch2];
		}

		leftDrive(leftSpeed);
		rightDrive(rightSpeed);

		/*				!!!		MOBILE GOAL CARRIER CONTROLS		!!!

		Pressing Button 6U should bring the mobile goal carrier in
		Pressing Button 6D should bring the mobile goal carrier out

		CHANGE VALUES
		When contracted, pot =
		When extended, pot =
		*/
		if(vexRT[Btn6U] == 1 && SensorValue[mobileAngle] <2403)
		{
			motor[mobileGoal] = 127;
		}
		else if(vexRT[Btn6D] == 1 && SensorValue[mobileAngle] > 348)
		{
			motor[mobileGoal] = -127;
		}
		else
		{
			motor[mobileGoal] = 0;
		}



		/******** SECOND REMOTE CONTROL *********
		Controls the 2 subsystems of the arm.
		and intakes the yellow cones

		ADVICE: SHOULD MAKE BOTH ARMBASE AND ARMSWING CONTROLS VIA JOYSTICK
			FOR MORE MANUAL CONTROL
		*/
		/* 				!!!			ARM BASE CONTROLS			!!!
		Pressing button 6U on the second remote lifts the arm up
		Pressing button 6D on the second remote lowers the arm.
		*/
		if (vexRT[Btn6UXmtr2]==1) {
			motor[armBase] = -60;
		}
		else if (vexRT[Btn6DXmtr2]==1) {
			motor[armBase] = 60;
		}
		else {
			motor[armBase] = 0;
		}


		//Contorls the secondary arm
		if (vexRT[Btn5UXmtr2]==1)
		{
			motor[armSwing] = 60;
		}
		else if (vexRT[Btn5DXmtr2] == 1)
		{
			motor[armSwing] = -60;
		}
		else
		{
			motor[armSwing] = 0;
		}


		//Controls golaith intake
		if (vexRT[Btn8UXmtr2]==1)
		{
			motor[grabber] = 127;
		}
		else if (vexRT[Btn8DXmtr2]==1)
		{
			motor[grabber] = -127;
		}
		else {
			motor[grabber] = 0;
		}


		//light controls
		//turning light on (0 = on)
		if (vexRT[Btn7R] == 1)
		{
			SensorValue[rightLights] = 0;
			SensorValue[leftLights] = 0;
		}
		//turning light off (1 = off)
		else if (vexRT[Btn8L] == 1)
		{
			SensorValue[rightLights] = 1;
			SensorValue[leftLights] = 1;
		}
	}
}
