#pragma config(Sensor, in1,    armLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           leftFront,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           leftMid,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftBack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightMid,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightBack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightLift,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!
//		THIS PROGRAM IS SET ON 4-WHEEL DRIVE! GO REFER 11040.C FILE FOR 2-MOTOR DRIVE

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.

	SensorType[in3] = sensorNone;
	wait1Msec(1000);
	SensorType[in3] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro] = 0; //positive counterclockwise

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

  bStopTasksBetweenModes = false;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                         */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void moveForward(int speed) {
	motor[leftDrive] = speed;
	motor[rightDrive] = speed;
}
void liftFixedArm(int speed) {
	motor[leftArmFix] = speed;
	motor[rightArmFix] = speed;
}
void liftLiftArm(int speed) {
	motor[leftLift] = speed;
	motor[rightLift] = speed;
}
task autonomous()
{
  // ..........................................................................
  // Insert user code here./*
  // THIS IS WHERE THAT 20-SEC AUTONOMOUS CODING GOES INTO!!!!!!!!!!
  //DONT JUST COPY AND PASTE!! CHECK FOR SYNTAX AND LOGIC ERRORS!!!!!!


  // ..........................................................................

  // Remove this function call once you have "real" code.
	liftFixedArm(80);
	wait1Msec(2500);
	liftFixedArm(0);
	liftLiftArm(80);
	wait1Msec(1200);
	liftLiftArm(0);
  moveForward(30);
  wait1Msec(1400);
  moveForward(0);
  liftLiftArm(-80);
  wait1Msec(1200);
  motor[grabber]=-80;
  wait1Msec(500);
  motor[grabber]=0;
  liftLiftArm(0);
  liftLiftArm(80);
  wait1Msec(1200);
  liftLiftArm(0);
  moveForward(-30);
  wait1Msec(1400);
  moveForward(0);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  short leftSpeed;
	short rightSpeed;
	short armBaseCtrl;
	const short TIME_DEPLOY_CARRIER = 500;						//time to make a 90 deg angle for the mobile goal carrier
	const short LFIXED_ANGLE = 0;									//for the armFixed Pot
	const short HFIXED_ANGLE = 915;
	const short LLIFT_ANGLE = 1480;
	const short HLIFT_ANGLE = 2030;											//for the armLift Pot
	short grabberCtrl;
	short mobileGoalCtrl;

	while(true)
	{
			/*				!!!		DRIVE CONTROLS		!!!
			*/
			//To control the left side using channel 3
			if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
			{
				leftSpeed = 0;
			}
			else
			{
				leftSpeed = vexRT[Ch3];
			}

			//To control the right side using channel 2
			if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
			{
				rightSpeed = 0;
			}
			else
			{
				rightSpeed = vexRT[Ch2];
			}
			motor[leftDrive] = leftSpeed;
			motor[rightDrive] = rightSpeed;

			/*				!!!		BASE ARM CONTROLS		!!!

			Pressing Button 6U should lift entire arm up
			Pressing Button 6D should drag entire arm down
			*/
			const short fixedSpeed = 80;
			const short liftSpeed = 80;
			if (vexRT[Btn6U] == 1) {
				motor[leftArmFix] = fixedSpeed;
				motor[rightArmFix] = fixedSpeed;
			}
			else if (vexRT[Btn6D] == 1) {
				motor[leftArmFix] = -fixedSpeed;
				motor[rightArmFix] = -fixedSpeed;
			}
			else {
				motor[leftArmFix] = 0;
				motor[rightArmFix] = 0;
			}

			if (vexRT[Btn5U] == 1) {
				motor[leftLift] = liftSpeed;
				motor[rightLift] = liftSpeed;
			}
			else if (vexRT[Btn5D] == 1) {
				motor[leftLift] = -liftSpeed;
				motor[rightLift] = -liftSpeed;
			}
			else {
				motor[leftLift] = 0;
				motor[rightLift] = 0;
			}
			/*armBaseCtrl = (vexRT[Btn6U] << 1) + vexRT[Btn6D];
			int armSpeed = 60;
			switch (armBaseCtrl)
			{
					case 1: //going down
							if (SensorValue[armLift] > LLIFT_ANGLE)
							{
								motor[leftArmFix] = -armSpeed;
								motor[rightArmFix] = -armSpeed;
								motor[leftLift] = -armSpeed;
								motor[rightLift] = -armSpeed;
							}
							else if (SensorValue[armFixed] > LFIXED_ANGLE)
							{
								motor[leftArmFix] = -armSpeed;
								motor[rightArmFix] = -armSpeed;
							}
							break;
					case 2: //going up
							if (SensorValue[armFixed] < HFIXED_ANGLE)
							{
								motor[leftArmFix] = armSpeed;
								motor[rightArmFix] = armSpeed;
								motor[leftLift] = armSpeed;
								motor[rightLift]= armSpeed;
							}
							else if (SensorValue[armLift] < HLIFT_ANGLE)
							{
								motor[leftLift] = armSpeed;
								motor[rightLift]= armSpeed;
							}
							break;
					default:
							motor[leftArmFix] = 0;
							motor[rightArmFix] = 0;
							break;
			}
			*/
			/*				!!!		GRABBER CONTROLS		!!!

			Pressing Button 8L should open the grabber
			Pressing Button 8R should close the grabber
			*/
			grabberCtrl = (vexRT[Btn8L] << 1) + vexRT[Btn8R];
			switch (grabberCtrl)
			{
					case 1:						//close
							motor[grabber] = -70;
							wait1Msec(250);
							motor[grabber] = 0;
							break;
					case 2:						//open
							motor[grabber] = 70;
							wait1Msec(250);
							motor[grabber] = 0;
							break;
					default:
							motor[grabber] = 0;
							break;
			 }



			/*				!!!		MOBILE GOAL CARRIER CONTROLS		!!!

					Pressing Button 8U should bring the mobile goal carrier up
					Pressing Button 8D should bring the mobile goal carrier down
			*/
			/*
			mobileGoalCtrl = (vexRT[Btn8D] << 1) + vexRT[Btn8U];
			switch (mobileGoalCtrl)
			{
					case 1:																//Bring carrier up
							motor[mobileGoal] = -127;
							wait1Msec(TIME_DEPLOY_CARRIER * 2);

							//to bring the armLifts down after setting the mobile goal in place
							motor[leftLift] = -127;
							motor[rightLift] = -127;
							wait1Msec(1000);
							motor[leftLift] = 0;
							motor[rightLift] = 0;

							break;
					case 2:																// Bring carrier down
							//to bring the armLifts up to prevent interferance with stacked yellow cones
							motor[leftLift] = 127;
							motor[rightLift] = 127;
							wait1Msec(1000);
							motor[leftLift] = 0;
							motor[rightLift] = 0;
							motor[mobileGoal] = 127;
							wait1Msec(TIME_DEPLOY_CARRIER);
							break;
					default:
							motor[mobileGoal] = 0;
							break;
			}*/
	}
  }
