#pragma config(Motor,  port1,           LeftArm,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftArmPinch,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightArmPinch, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		bool LeftArm;
		bool RightArm;
		bool LeftArmPinch;
		bool RightArmPinch;

		void driveForward () {
			motor [LeftArm] = 127;
			motor [RightArm] = 127; //Reversed
			wait1Msec (3000); //Continues for 3 seconds
		}

		void driveBackward () {
			motor [LeftArm] = -127;
			motor [RightArm] = -127; //Reversed
			wait1Msec (3000); //Continues for 3 seconds
		}

		void pinchClose () {
			motor [LeftArmPinch] = 63;
			motor [RightArmPinch] = 0; //Reversed
			wait1Msec (3000); //Continued for 3 seconds
		}

		void pinchOpen () {
			motor [LeftArm] = 0;
			motor [RightArm] = 63; //Reversed
			wait1Msec (3000); //Continued for 3 seconds
		}

	}
}
