#pragma config(Motor,  port1,           rightArm,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightPinch,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftPinch,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Initializes pinch speeds and connects motors to specific speed values
	int leftArmSpeed;
	int rightArmSpeed;
	motor [leftArm] = leftPinchSpeed;
	motor [rightArm] = rightPinchSpeed;

	//DEFAULT ARM MOVEMENT FUNCTION
	while (true)
	{
		wait(4); //Waits for robot to reach blue cone

		//Function: Lowers tray to pick up blue cone when 6D button is activated
		if (vexRT[Btn6U] == 1)
		{
			leftArmSpeed = -127;
			rightPinchSpeed = -127;
		}
		else
		{
			leftArmSpeed = 0;
			rightArmSpeed = 0;
		}
		
		wait(2); //Waits two seconds the robot can move forward and pick up blue cone
		
		//Function: Raised tray along with blue cone 
		if (vexRT[Btn6D] == 1)
		{
			leftArmSpeed = 127;
			rightArmSpeed = 127;
		}
		
		wait(6); //Waits for robot to reach our zone
	}
}
