#pragma config(Sensor, in1,    liftAngle,      sensorPotentiometer)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArmT,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           leftArmT,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           frontMotor,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rightArmB,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftArmB,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Code for VEX 11040B


task main()
{
	int leftSpeed;
	int rightSpeed;
	int armBaseSpeed;
	int rightArmSpeed;
	int leftArmSpeed;
	int grabberSpeed;
	bool ifMobileGoalActivated = false;

	while (true)
	{

		//Controls Right Front Wheel
		if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
			{
				rightSpeed = 0;
			}
		else
			{
				rightSpeed = vexRT[Ch2];
			}

		//Controls Left Front Wheel
		if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
			{
				leftSpeed = 0;
			}
		else
			{
				leftSpeed = vexRT[Ch3];
			}

		//Controls arm movement
		if (vexRT[Btn6U]==1 && SensorValue[liftAngle] < 1800) {
			armBaseSpeed = -110;
			grabberSpeed = 0;
		}
		else if (vexRT[Btn6D]==1 && SensorValue[liftAngle] > 1800) {
			armBaseSpeed = 110;
			//grabberSpeed = -30;
		}
		else {
			armBaseSpeed = 0;
			grabberSpeed = 0;
		}

		//Controls pinchers movement
		if (vexRT[Btn8U]==1)
			{
				grabberSpeed = 30;
			}
		else if (vexRT[Btn7U]==1)
			{
				grabberSpeed = -30;
			}
		else
			{
				grabberSpeed = 0;
			}


		motor[leftFront] = leftSpeed;
		motor[leftBack] = leftSpeed;
		motor[rightFront] = rightSpeed;
		motor[rightBack] = rightSpeed;
		motor[rightArmT] = armBaseSpeed;
		motor[rightArmB] = armBaseSpeed;
		motor[leftArmT] = armBaseSpeed;
		motor[leftArmB] = armBaseSpeed;
		motor[frontMotor] = grabberSpeed;
	}


}
