#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IMPORTANT NOTICES
DO NOT TOUCH THIS FILE

RC CODE FOR VEX ROBOT 11040B
*/

task main()
{
	int leftSpeed;
	int rightSpeed;
	//int armBaseSpeed;
	//int grabberSpeed;
	//bool ifMobileGoalActivated = false;

	while(true)
	{
		//DRIVE CONTROLS
		//To control the left side using channel 3
		if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
		{
			leftSpeed = 0;
		}
		else
		{
			leftSpeed = vexRT[Ch3];
		}



		/*
		//ARM CONTROLS
		//To control the right side using channel 2
		if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
		{
			rightSpeed = 0;
		}
		else
		{
			rightSpeed = vexRT[Ch2];
		}

		motor[leftDrive] = leftSpeed;
		motor[rightDrive] = rightSpeed;



		while (!ifMobileGoalActivated)
		{
			//lift up yeloow cones using Button 6U
			if (vexRT[Btn6U] == 1)
			{
				armBaseSpeed = 127;
			}
			//lift down yeloow cones using Button 6D
			else if (vexRT[Btn6D] == 1)
			{
				armBaseSpeed = -127;
			}
			else
			{
				armBaseSpeed = 0;
			}

			motor[leftTopBaseArm] = armBaseSpeed;
			motor[leftBottomBaseArm] = armBaseSpeed;
			motor[rightTopBaseArm] = armBaseSpeed;
			motor[rightBottomBaseArm] = armBaseSpeed;

			//opening graber using Botton 5U
			if (vexRT[Btn5U] == 1)
			{
				grabberSpeed = 127;
			}
			else if (vexRT[Btn5D] == 1)
			{
				grabberSpeed = -127;
			}
			else
			{
				grabberSpeed = 0;
			}
			motor[grabber] = grabberSpeed;

	 }
	 */

	}

}
