#pragma config(Sensor, in7,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoal,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoal2,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightMid,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMid,       tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Code for VEX 11040B
task main()
{
	short rightSpeed;
	short leftSpeed;
	short mobileSpeed;
	while (true)
	{
		//Controls Right Front Wheel

		if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
		{
			rightSpeed = 0;
		}
		else {
			rightSpeed = vexRT[Ch2];
		}

		//Controls Left Front Wheel

		if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
		{
			leftSpeed = 0;
		}
		else {
			leftSpeed = vexRT[Ch3];
		}

		//Controls Mobile Goal Lift
		if (vexRT[Btn5D]==1) {
			mobileSpeed = 127;
		}
		else if (vexRT[Btn5U]==1) {
			mobileSpeed = -127;
		}
		else {
			mobileSpeed = 0;
		}

		motor[rightBack] = rightSpeed;
		motor[rightFront] = rightSpeed;
		motor[rightMid] = rightSpeed;
		motor[leftBack] = leftSpeed;
		motor[leftFront] = leftSpeed;
		motor[leftMid] = leftSpeed;

		 motor[mobileGoal] = mobileSpeed;
		motor[mobileGoal2] = mobileSpeed;
	}
}
