#pragma config(Sensor, in1,    liftAngle,      sensorPotentiometer)
#pragma config(Sensor, in2,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in3,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobileLift2,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveForward(int speed) {
	motor[leftFront] = speed;
	motor[leftBack] = speed;
	motor[rightFront] = speed;
	motor[rightBack] = speed;
}

void liftArm(int speed) {
	motor[leftArm] = speed;
	motor[rightArm] = speed;
}

void moveMobileLift(int speed) {
	motor[mobileLift] = speed;
	motor[mobileLift2] = speed;
}

//Code for VEX 11040B
task main(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
  SensorType[in3] = sensorNone;
  wait1Msec(1000);
  //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in3] = sensorGyro;
  wait1Msec(2000);

	//Move Arm Back
	liftArm(-80);
	wait1Msec(1350);
	liftArm(0);

	//Lower Mobile Lift
	moveMobileLift(-127);
	wait1Msec(800);
	moveMobileLift(0);

	//Move Forward to get Mobile Goal
	moveForward(127);
	wait1Msec(2000);
	moveForward(0);

	//Pick up Mobile Goal
	moveMobileLift(127);
	wait1Msec(800);
	moveMobileLift(0);

	//Move Back a bit to clear for turning
	moveForward(-127);
	wait1Msec(1000);
	moveForward(0);

	//210 degree turn
	while (abs(SensorValue[in3]) < 2100) {
		motor[rightFront] = 127;
		motor[rightBack] = 127;
		motor[leftFront] = -127;
		motor[leftBack] = -127;
	}

	//Move at full speed into 20 point zone
	while (lineSensor > 200) {
		moveForward(127);
	}
	while (4 * PI * (sensorValue[leftEncoder]/360 < 1080);
  rightDistance = 4 * PI * (sensorValue[rightEncoder]/360);
	moveForward(0);

	//Lower Mobile Lift
	moveMobileLift(127);
	wait1Msec(800);
	moveMobileLift(0);

	//Move backwards
	moveForward(-127);
	wait1Msec(5000);
	moveForward(0);

	while (abs(SensorValue[in3]) > 0) {
		motor[rightFront] = -127;
		motor[rightBack] = -127;
		motor[leftFront] = 127;
		motor[leftBack] = 127;
	}

}
