#pragma config(Sensor, in1,    liftAngle,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobileLift2,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveForward(int speed) {
	motor[leftFront] = speed;
	motor[leftBack] = speed;
	motor[rightFront] = speed;
	motor[rightBack] = speed;
}

void liftArm(int speed) {

	motor[leftArm] = speed;

	motor[rightArm] = speed;

}

void liftMobileArm(int speed) {

  motor[mobileLift] = speed;

  motor[mobileLift2] = speed;

}

//Code for VEX 11040B

task main()

{
	/*
	while (true) {
		motor[rightFront] = 127;
		motor[rightBack] = 127;
		motor[leftFront] = 127;
		motor[leftBack] = 127;
	}*/
	int leftSpeed;

	int rightSpeed;

	int armBaseSpeed;

	int grabberSpeed;

	int mobileSpeed;

	SensorValue[rightEncoder] = 0;

	//Keep Grabber on the whole time
	motor[frontMotor] = -127;

	//Move Arm back for Preload
	liftArm(-60);
	wait1Msec(1000);
	liftArm(0);
	//Lower Mobile Goal Lift

	liftMobileArm(127);
	wait1Msec(800);
	liftMobileArm(0);

	//Move Forward Towards Mobile Goal
	while (4 * PI * (SensorValue[rightEncoder] / 360) < 60) {
		moveForward(80);
	}
	moveForward(0);

	//Raise Mobile Goal Lift
	liftMobileArm(-127);
	wait1Msec(800);
	liftMobileArm(0);

	//Stack Preload
	liftArm(60);
	wait1Msec(1000);
	liftArm(0);

	//Move Backwards
	while (4 * PI * (SensorValue[rightEncoder] / 360) > 0) {
		moveForward(-80);
	}
	moveForward(0);



}
