#pragma config(Sensor, in1,    armLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           rightMid,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBBack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftArms,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMid,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!
// 			!!!			VEX 11040A		!!!


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.

	SensorType[in3] = sensorNone;
	wait1Msec(1000);
	SensorType[in3] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro] = 0; //positive counterclockwise

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	bStopTasksBetweenModes = false;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

void leftDrive(short speed)
{
	motor[leftFront] = speed;
	motor[leftMid] = speed;
	motor[leftBack] = speed;
	motor[leftBBack] = speed;
}

void rightDrive(short speed)
{
	motor[rightFront] = speed;
	motor[rightMid] = speed;
	motor[rightBack] = speed;
	motor[rightBBack] = speed;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                         */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	/*
	short mobileDist = 1200;

	//Lower Lift
	motor[liftArms] = -60;
	wait1Msec(900);
	motor[liftArms] = 0;

	//Move Forward
	while (SensorValue[rightEncoder] < mobileDist || SensorValue[leftEncoder] < mobileDist) {
		if (SensorValue[rightEncoder] > SensorValue[leftEncoder]) {
			leftDrive(100);
			rightDrive(0);
		}
		else if (SensorValue[leftEncoder] > SensorValue[rightEncoder])
		{
			rightDrive(100);
			leftDrive(0);

		}
	}
		leftDrive(0);
		rightDrive(0);
		//Lift Mobile Goal
		motor[liftArms] = 60;
		wait1Msec(900);
		motor[liftArms] = 0;

		//Move Backward
		while (SensorValue[rightEncoder] > 800 || SensorValue[leftEncoder] > 800) {
			if (SensorValue[rightEncoder] < SensorValue[leftEncoder]) {
				leftDrive(-100);
				rightDrive(0);
			}
			else if (SensorValue[leftEncoder] < SensorValue[rightEncoder])
			{
				leftDrive(0);
				rightDrive(-100);
			}
			else {
				leftDrive(-100);
				rightDrive(-100);
			}
		}
		leftDrive(0);
		rightDrive(0);
		while (abs(SensorValue[gyro]) < 1350) {
			rightDrive(100);
			leftDrive(0);
		}
		leftDrive(127);
		rightDrive(127);
		wait1Msec(1500);    //chris can suck the big d
		leftDrive(0);
		rightDrive(0);
	*/
	}

	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

task usercontrol()
{
	short leftSpeed;
	short rightSpeed;

	/*				!!!		DRIVE CONTROLS		!!!
		*/
		//To control the left side using channel 3
		if (vexRT[Ch3] > -35 && vexRT[Ch3] < 35)
		{
			leftSpeed = 0;
		}
		else
		{
			leftSpeed = vexRT[Ch3];
		}

		//To control the right side using channel 2
		if (vexRT[Ch2] > -35 && vexRT[Ch2] < 35)
		{
			rightSpeed = 0;
		}
		else
		{
			rightSpeed = vexRT[Ch2];
		}

		leftDrive(leftSpeed);
		rightDrive(rightSpeed);

		/*				!!!		MOBILE GOAL CARRIER CONTROLS		!!!

		Pressing Button 6U should bring the mobile goal carrier in
		Pressing Button 6D should bring the mobile goal carrier out

		When contracted, pot = 3330
		When extended, pot = 1425
		*/
		if(vexRT[Btn6U] == 1 && SensorValue[armLift] <3325)
		{
			motor[liftArms] = 127;
		}
		else if(vexRT[Btn6D] == 1 && SensorValue[armLift] > 1420)
		{
			motor[liftArms] = -127;
		}
		else
		{
			motor[liftArms] = 0;
		}






		/*
		//light control (if getting one... VEX inverse the controls... idk y)
		//turning light on (0 = on)
		if (vexRT[Btn7R] == 1)
		{
			SensorValue[lights] = 0;
		}
		//turning light off (1 = off)
		else if (vexRT[Btn8L] == 1)
		{
			SensorValue[lights] = 1;
		}
		*/
}
