#pragma config(Sensor, in1,    armLift,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lights,         sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           rightMid,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBBack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftArms,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMid,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorVex393_HBridge, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// RC CODE FOR THE NEW VEX ROBOT 11040A 8-MOTOR DRIVE

void leftDrive(short speed)
{
	motor[leftFront] = speed;
	motor[leftMid] = speed;
	motor[leftBack] = speed;
	motor[leftBBack] = speed;
}

void rightDrive(short speed)
{
	motor[rightFront] = speed;
	motor[rightMid] = speed;
	motor[rightBack] = speed;
	motor[rightBBack] = speed;
}

void moveForward(short speed) {
	leftDrive(speed);
	rightDrive(speed);
}

task main()
{
	short leftSpeed;
	short rightSpeed;
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro] = 0; //positive counterclockwise
	SensorValue[rightEncoder] = 0;

	//Lower the mobile goal carrier
	motor[liftArms] = -127;
	wait1Msec(1500);
	motor[liftArms] = 0;

	//Move forward to pick up mobile goal
	while ( (4 * PI * (SensorValue[rightEncoder] / 720) ) < 60 ) {
		moveForward(50);	
	}
	moveForward(0);
	
	//Raise the mobile goal carrier
	motor[liftArms] = 127;
	wait1Msec(3000);
	motor[liftArms] = 0;

	//Move backward
	while ( (4 * PI * (SensorValue[rightEncoder] / 720) ) > 0 ) {
		moveForward(-50);
	}
	moveForward(0);

	//Turn left by 120 degrees
	while (abs(SensorValue[gyro]) < 1350) {
		rightDrive(50);
	}
	rightDrive(0);
	
	SensorValue[rightEncoder] = 0;
	//Move forward a little bit
	while ( ( 4 * PI * (SensorValue[rightEncoder] / 720) ) < 60) {
		moveForward(50);
	}
	moveForward(0);
	
	SensorValue[gyro] = 0;
	
	//Turn towards 20 point zone
	while (abs(SensorValue[gyro]) < 900) {
		rightDrive(50);
	}
	rightDrive(0);
	
	//Full speed into 20 Point Zone
	moveForward(100);
	wait1Msec(1500);
	moveForward(0);
	
	//Lower the mobile goal carrier
	motor[liftArms] = -127;
	wait1Msec(3000);
	motor[liftArms] = 0;
	
	//Move backward
	moveForward(-100);
	wait1Msec(1500);
	moveForward(0);
}
